import {
    PaymentTransactionFormSchema,
    PaymentTransactionUpdateSchema,
} from "@/components/Zod";

export const paymentTransactionFormConfig = {
    contexts: {
        "payment-transaction-add": {
            mode: "add",
            title: "Add Payment Transaction",
            api: {
                method: "POST",
                endpoint: "payment-transaction-add",
                module: "payment-transaction",
            },
            schema: PaymentTransactionFormSchema,
            submitButtonText: "Add Payment Transaction",
            loadingButtonText: "Creating...",
            successMessage: "Payment Transaction created successfully",
            fields: [
                {
                    name: "customerId",
                    label: "Customer",
                    type: "customer-select",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "currencyId",
                    label: "Customer Currency",
                    type: "currency-select",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "bankBookId",
                    label: "Bank Account",
                    type: "bank-book-select",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "companyId",
                    label: "Company",
                    type: "company-select",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "paymentMode",
                    label: "Payment Mode",
                    type: "select",
                    required: true,
                    defaultValue: "Cash",
                    readOnly: false,
                    hidden: false,
                    options: [
                        { label: "Cash", value: "Cash" },
                        { label: "Credit Card", value: "Credit Card" },
                        { label: "Debit Card", value: "Debit Card" },
                        { label: "Digital Wallet", value: "Digital Wallet" },
                        { label: "Bank Transfer", value: "Bank Transfer" },
                        { label: "UPI", value: "UPI" },
                        { label: "Buy Now Pay Later", value: "Buy Now Pay Later" },
                    ],
                },
                {
                    name: "paymentDate",
                    label: "Payment Date",
                    type: "date",
                    required: true,
                    defaultValue: new Date().toISOString().split("T")[0],
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "exchangeRate",
                    label: "Exchange Rate",
                    type: "number",
                    placeholder: "Auto-filled on currency selection",
                    required: true,
                    defaultValue: "",
                    readOnly: true,
                    hidden: false,
                },
                {
                    name: "exchangeDate",
                    label: "Exchange Date",
                    type: "date",
                    required: true,
                    defaultValue: new Date().toISOString().split("T")[0],
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "narration",
                    label: "Narration",
                    type: "text",
                    placeholder: "e.g. Payment for Invoice #1024",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "transactionAmount",
                    label: "Transaction Amount",
                    type: "number",
                    placeholder: "e.g. 1500.00",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "baseAmount",
                    label: "Base Amount",
                    type: "number",
                    placeholder: "Auto-calculated",
                    required: false,
                    defaultValue: "",
                    readOnly: true,
                    hidden: false,
                },
                {
                    name: "description",
                    label: "Description",
                    type: "textarea",
                    placeholder: "Additional payment details...",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
            ],
        },
        "payment-transaction-update": {
            mode: "update",
            title: "Edit Payment Transaction",
            api: {
                fetchEndpoint: "payment-transaction-details",
                method: "PUT",
                endpoint: "payment-transaction-update",
                module: "payment-transaction",
            },
            schema: PaymentTransactionUpdateSchema,
            submitButtonText: "Update Payment Transaction",
            loadingButtonText: "Updating...",
            successMessage: "Payment Transaction updated successfully",
            fields: [
                {
                    name: "customerId",
                    label: "Customer",
                    type: "customer-select",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "currencyId",
                    label: "Customer Currency",
                    type: "currency-select",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "bankBookId",
                    label: "Bank Account",
                    type: "bank-book-select",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "companyId",
                    label: "Company",
                    type: "company-select",
                    required: true,
                    defaultValue: "",
                    readOnly: true,
                    hidden: false,
                },
                {
                    name: "paymentMode",
                    label: "Payment Mode",
                    type: "select",
                    required: true,
                    defaultValue: "Cash",
                    readOnly: false,
                    hidden: false,
                    options: [
                        { label: "Cash", value: "Cash" },
                        { label: "Credit Card", value: "Credit Card" },
                        { label: "Debit Card", value: "Debit Card" },
                        { label: "Digital Wallet", value: "Digital Wallet" },
                        { label: "Bank Transfer", value: "Bank Transfer" },
                        { label: "UPI", value: "UPI" },
                        { label: "Buy Now Pay Later", value: "Buy Now Pay Later" },
                    ],
                },
                {
                    name: "paymentDate",
                    label: "Payment Date",
                    type: "date",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "exchangeRate",
                    label: "Exchange Rate",
                    type: "number",
                    placeholder: "Auto-filled on currency selection",
                    required: true,
                    defaultValue: "",
                    readOnly: true,
                    hidden: false,
                },
                {
                    name: "exchangeDate",
                    label: "Exchange Date",
                    type: "date",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "narration",
                    label: "Narration",
                    type: "text",
                    placeholder: "e.g. Payment for Invoice #1024",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "transactionAmount",
                    label: "Transaction Amount",
                    type: "number",
                    placeholder: "e.g. 1500.00",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "baseAmount",
                    label: "Base Amount",
                    type: "number",
                    placeholder: "Auto-calculated",
                    required: false,
                    defaultValue: "",
                    readOnly: true,
                    hidden: false,
                },
                {
                    name: "description",
                    label: "Description",
                    type: "textarea",
                    placeholder: "Additional payment details...",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
            ],
        },
    },
};
