import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LoginContext from "@/components/hooks/LoginContext";
import { ToastContainer } from "react-toastify";
import UserListContext from "@/components/hooks/UserListContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* <Head>
        <link rel="icon" href="/logo.png" />
      </Head> */}
      <LoginContext>
        <UserListContext>
          <body className="min-h-full flex flex-col">
            {children}
            <ToastContainer />
          </body>
        </UserListContext>
      </LoginContext>
    </html>
  );
}
