import { BankBookFormSchema, BankBookUpdateSchema } from "../../Zod";

export const bankBookFormConfig = {
    contexts: {
        "bank-book-add": {
            mode: "add",
            title: "Add Bank Book",
            api: {
                method: "POST",
                endpoint: "bank-book-add",
                module: "bank-book",
            },
            schema: BankBookFormSchema,
            submitButtonText: "Add Bank Book",
            loadingButtonText: "Creating...",
            successMessage: "Bank Book created successfully",
            fields: [
                {
                    name: "bankBookName",
                    label: "Bank Book Name",
                    type: "text",
                    placeholder: "e.g. HDFC Operating Account",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "companyId",
                    label: "Company",
                    type: "company-select",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "bankId",
                    label: "Bank",
                    type: "select",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "currencyId",
                    label: "Currency",
                    type: "select",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "beneficiaryName",
                    label: "Beneficiary Name",
                    type: "text",
                    placeholder: "e.g. Acme Corp Ltd",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "accountNumber",
                    label: "Account Number",
                    type: "text",
                    placeholder: "e.g. 5010023456789",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "branchName",
                    label: "Branch Name",
                    type: "text",
                    placeholder: "e.g. Downtown Main Branch",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "remarks",
                    label: "Remarks",
                    type: "textarea",
                    placeholder: "Additional notes...",
                    required: false,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "status",
                    label: "Status",
                    type: "select",
                    required: true,
                    defaultValue: "Active",
                    readOnly: false,
                    hidden: false,
                    options: [
                        { label: "Active", value: "Active" },
                        { label: "Inactive", value: "Inactive" },
                    ],
                },
            ],
        },
        "bank-book-update": {
            mode: "update",
            title: "Edit Bank Book",
            api: {
                fetchEndpoint: "bank-book-details",
                method: "PUT",
                endpoint: "bank-book-update",
                module: "bank-book",
            },
            schema: BankBookUpdateSchema,
            submitButtonText: "Update Bank Book",
            loadingButtonText: "Updating...",
            successMessage: "Bank Book updated successfully",
            fields: [
                {
                    name: "bankBookCode",
                    label: "Bank Book Code",
                    type: "text",
                    required: false,
                    defaultValue: "",
                    readOnly: true,
                    hidden: false,
                },
                {
                    name: "bankBookName",
                    label: "Bank Book Name",
                    type: "text",
                    placeholder: "e.g. HDFC Operating Account",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "companyId",
                    label: "Company",
                    type: "company-select",
                    required: true,
                    defaultValue: "",
                    readOnly: true,
                    hidden: false,
                },
                {
                    name: "bankId",
                    label: "Bank",
                    type: "select",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "currencyId",
                    label: "Currency",
                    type: "select",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "beneficiaryName",
                    label: "Beneficiary Name",
                    type: "text",
                    placeholder: "e.g. Acme Corp Ltd",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "accountNumber",
                    label: "Account Number",
                    type: "text",
                    placeholder: "e.g. 5010023456789",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "branchName",
                    label: "Branch Name",
                    type: "text",
                    placeholder: "e.g. Downtown Main Branch",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "remarks",
                    label: "Remarks",
                    type: "textarea",
                    placeholder: "Additional notes...",
                    required: false,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "status",
                    label: "Status",
                    type: "select",
                    required: true,
                    defaultValue: "Active",
                    readOnly: false,
                    hidden: false,
                    options: [
                        { label: "Active", value: "Active" },
                        { label: "Inactive", value: "Inactive" },
                    ],
                },
            ],
        },
    },
};
