import { BankFormSchema, BankUpdateSchema } from "../../Zod";

export const bankFormConfig = {
    contexts: {
        "bank-add": {
            mode: "add",
            title: "Add Bank",
            api: {
                method: "POST",
                endpoint: "bank-add",
                module: "bank",
            },
            schema: BankFormSchema,
            submitButtonText: "Add Bank",
            loadingButtonText: "Creating...",
            successMessage: "Bank created successfully",
            fields: [
                {
                    name: "bankName",
                    label: "Bank Name",
                    type: "text",
                    placeholder: "e.g. Chase, HSBC, HDFC",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "companyId",
                    label: "Company",
                    type: "company-select",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "remarks",
                    label: "Remarks",
                    type: "textarea",
                    placeholder: "Additional notes...",
                    required: false,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "status",
                    label: "Status",
                    type: "select",
                    required: true,
                    defaultValue: "Active",
                    readOnly: false,
                    hidden: false,
                    options: [
                        { label: "Active", value: "Active" },
                        { label: "Inactive", value: "Inactive" },
                    ],
                },
            ],
        },
        "bank-update": {
            mode: "update",
            title: "Edit Bank",
            api: {
                fetchEndpoint: "bank-details",
                method: "PUT",
                endpoint: "bank-update",
                module: "bank",
            },
            schema: BankUpdateSchema,
            submitButtonText: "Update Bank",
            loadingButtonText: "Updating...",
            successMessage: "Bank updated successfully",
            fields: [
                {
                    name: "bankName",
                    label: "Bank Name",
                    type: "text",
                    placeholder: "e.g. Chase, HSBC, HDFC",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "companyId",
                    label: "Company",
                    type: "company-select",
                    required: true,
                    defaultValue: "",
                    readOnly: true,
                    hidden: false,
                },
                {
                    name: "remarks",
                    label: "Remarks",
                    type: "textarea",
                    placeholder: "Additional notes...",
                    required: false,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "status",
                    label: "Status",
                    type: "select",
                    required: true,
                    defaultValue: "Active",
                    readOnly: false,
                    hidden: false,
                    options: [
                        { label: "Active", value: "Active" },
                        { label: "Inactive", value: "Inactive" },
                    ],
                },
            ],
        },
    },
};
