import { BrandFormSchema, BrandUpdateSchema } from "../../Zod";

export const brandFormConfig = {
    contexts: {
        "brand-add": {
            mode: "add",
            title: "Brand",
            api: {
                method: "POST",
                endpoint: "brand-add",
                module: "brand",
            },
            schema: BrandFormSchema,
            submitButtonText: "Save",
            loadingButtonText: "Creating...",
            successMessage: "Brand created successfully",
            fields: [
                {
                    name: "brandName",
                    label: "Brand Name",
                    type: "text",
                    required: true,
                    placeholder: "Enter Brand Name",
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "companyId",
                    label: "Company",
                    type: "company-select",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "manufacturerId",
                    label: "Manufacturer",
                    type: "manufacturer-select",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "status",
                    label: "Status",
                    type: "select",
                    required: true,
                    defaultValue: "Active",
                    readOnly: false,
                    hidden: false,
                    options: [
                        { label: "Active", value: "Active" },
                        { label: "Inactive", value: "Inactive" },
                    ],
                },
            ],
        },
        "brand-update": {
            mode: "update",
            title: "Edit Brand",
            api: {
                fetchEndpoint: "brand-details",
                method: "PUT",
                endpoint: "brand-update",
                module: "brand",
            },
            schema: BrandUpdateSchema,
            submitButtonText: "Update Brand",
            loadingButtonText: "Updating...",
            successMessage: "Brand updated successfully",
            fields: [
                {
                    name: "brandName",
                    label: "Brand Name",
                    type: "text",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "companyId",
                    label: "Company",
                    type: "company-select",
                    required: true,
                    defaultValue: "",
                    readOnly: true,
                    hidden: false,
                },
                {
                    name: "manufacturerId",
                    label: "Manufacturer",
                    type: "manufacturer-select",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "status",
                    label: "Status",
                    type: "select",
                    required: true,
                    defaultValue: "Active",
                    readOnly: false,
                    hidden: false,
                    options: [
                        { label: "Active", value: "Active" },
                        { label: "Inactive", value: "Inactive" },
                    ],
                },
            ],
        },
    },
};
