import { UomFormSchema, UomUpdateSchema } from "../../Zod";

export const uomFormConfig = {
    contexts: {
        "uom-add": {
            mode: "add",
            title: "UOM",
            api: {
                method: "POST",
                endpoint: "uom-add",
                module: "uom",
            },
            schema: UomFormSchema,
            submitButtonText: "Save",
            loadingButtonText: "Creating...",
            successMessage: "UOM created successfully",
            fields: [
                {
                    name: "uomName",
                    label: "UOM Name",
                    type: "text",
                    placeholder: "e.g. Kilogram, Meter, Piece",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "abbreviation",
                    label: "Abbreviation",
                    type: "text",
                    placeholder: "e.g. kg, mtr, pcs",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "isoCode",
                    label: "ISO Code",
                    type: "text",
                    placeholder: "e.g. KGM, MTR, PCS",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "companyId",
                    label: "Company",
                    type: "company-select",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "status",
                    label: "Status",
                    type: "select",
                    required: true,
                    defaultValue: "Active",
                    readOnly: false,
                    hidden: false,
                    options: [
                        { label: "Active", value: "Active" },
                        { label: "Inactive", value: "Inactive" },
                    ],
                },
            ],
        },
        "uom-update": {
            mode: "update",
            title: "Edit UOM",
            api: {
                fetchEndpoint: "uom-details",
                method: "PUT",
                endpoint: "uom-update",
                module: "uom",
            },
            schema: UomUpdateSchema,
            submitButtonText: "Update UOM",
            loadingButtonText: "Updating...",
            successMessage: "UOM updated successfully",
            fields: [
                {
                    name: "uomName",
                    label: "UOM Name",
                    type: "text",
                    placeholder: "e.g. Kilogram, Meter, Piece",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "abbreviation",
                    label: "Abbreviation",
                    type: "text",
                    placeholder: "e.g. kg, mtr, pcs",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "isoCode",
                    label: "ISO Code",
                    type: "text",
                    placeholder: "e.g. KGM, MTR, PCS",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "companyId",
                    label: "Company",
                    type: "company-select",
                    required: true,
                    defaultValue: "",
                    readOnly: true,
                    hidden: false,
                },
                {
                    name: "status",
                    label: "Status",
                    type: "select",
                    required: true,
                    defaultValue: "Active",
                    readOnly: false,
                    hidden: false,
                    options: [
                        { label: "Active", value: "Active" },
                        { label: "Inactive", value: "Inactive" },
                    ],
                },
            ],
        },
    },
};
