import { TaxGroupFormSchema, TaxGroupUpdateSchema } from "../../Zod";

export const taxGroupFormConfig = {
    contexts: {
        "taxGroup-add": {
            mode: "add",
            title: "Add Tax Group",
            api: {
                method: "POST",
                endpoint: "tax-group-add",
                module: "tax-group",
            },
            schema: TaxGroupFormSchema,
            submitButtonText: "Add Tax Group",
            loadingButtonText: "Creating...",
            successMessage: "Tax Group created successfully",
            fields: [
                {
                    name: "taxName",
                    label: "Tax Name",
                    type: "text",
                    placeholder: "e.g. GST 18%",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "taxValue",
                    label: "Tax Value (%)",
                    type: "number",
                    placeholder: "e.g. 18",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "companyId",
                    label: "Company",
                    type: "company-select",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
            ],
        },
        "taxGroup-update": {
            mode: "update",
            title: "Edit Tax Group",
            api: {
                fetchEndpoint: "tax-group-details",
                method: "PUT",
                endpoint: "tax-group-update",
                module: "tax-group",
            },
            schema: TaxGroupUpdateSchema,
            submitButtonText: "Update Tax Group",
            loadingButtonText: "Updating...",
            successMessage: "Tax Group updated successfully",
            fields: [
                {
                    name: "taxName",
                    label: "Tax Name",
                    type: "text",
                    placeholder: "e.g. GST 18%",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "taxValue",
                    label: "Tax Value (%)",
                    type: "number",
                    placeholder: "e.g. 18",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "companyId",
                    label: "Company",
                    type: "company-select",
                    required: true,
                    defaultValue: "",
                    readOnly: true,
                    hidden: false,
                },
            ],
        },
    },
};
