import { CustomerFormSchema, CustomerUpdateSchema } from "../../Zod";

export const customerFormConfig = {
    contexts: {
        "customer-add": {
            mode: "add",
            title: "Add Customer",
            api: {
                method: "POST",
                endpoint: "customer-add",
                module: "customer",
            },
            schema: CustomerFormSchema,
            submitButtonText: "Add Customer",
            loadingButtonText: "Creating...",
            successMessage: "Customer created successfully",
            fields: [
                {
                    name: "customerName",
                    label: "Customer Name",
                    type: "text",
                    placeholder: "e.g. Acme Corp, Globex",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "customerEmail",
                    label: "Customer Email",
                    type: "email",
                    placeholder: "e.g. contact@acme.com",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "customerLogo",
                    label: "Customer Logo",
                    type: "file",
                    required: false,
                    readOnly: false,
                },
                {
                    name: "customerIncorporationDate",
                    label: "Incorporation Date",
                    type: "date",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "dialCode",
                    label: "Dial Code",
                    type: "number",
                    placeholder: "e.g. 91",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "phone",
                    label: "Phone",
                    type: "text",
                    placeholder: "e.g. 9876543210",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "companyId",
                    label: "Company",
                    type: "company-select",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "country",
                    label: "Country",
                    type: "text",
                    placeholder: "e.g. India, USA",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "state",
                    label: "State",
                    type: "text",
                    placeholder: "e.g. Maharashtra, California",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "city",
                    label: "City",
                    type: "text",
                    placeholder: "e.g. Mumbai, Los Angeles",
                    required: false,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "AddressLineOne",
                    label: "Address Line 1",
                    type: "text",
                    placeholder: "e.g. 123 Main St",
                    required: false,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "postalCode",
                    label: "Postal Code",
                    type: "number",
                    placeholder: "e.g. 400001",
                    required: false,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "ownerFirstName",
                    label: "Owner First Name",
                    type: "text",
                    placeholder: "e.g. John",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "ownerLastName",
                    label: "Owner Last Name",
                    type: "text",
                    placeholder: "e.g. Doe",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "ownerEmail",
                    label: "Owner Email",
                    type: "email",
                    placeholder: "e.g. john.doe@acme.com",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "ownerPhone",
                    label: "Owner Phone",
                    type: "text",
                    placeholder: "e.g. 9876543210",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "ownerDialCode",
                    label: "Owner Dial Code",
                    type: "number",
                    placeholder: "e.g. 91",
                    required: false,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "ownerDob",
                    label: "Owner Date of Birth",
                    type: "date",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "status",
                    label: "Status",
                    type: "select",
                    required: true,
                    defaultValue: "Active",
                    readOnly: false,
                    options: [
                        { label: "Active", value: "Active" },
                        { label: "Inactive", value: "Inactive" },
                    ],
                },
            ],
        },
        "customer-update": {
            mode: "update",
            title: "Edit Customer",
            api: {
                fetchEndpoint: "customer-details",
                method: "PUT",
                endpoint: "customer-update",
                module: "customer",
            },
            schema: CustomerUpdateSchema,
            submitButtonText: "Update Customer",
            loadingButtonText: "Updating...",
            successMessage: "Customer updated successfully",
            fields: [
                {
                    name: "customerName",
                    label: "Customer Name",
                    type: "text",
                    placeholder: "e.g. Acme Corp, Globex",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "customerEmail",
                    label: "Customer Email",
                    type: "email",
                    placeholder: "e.g. contact@acme.com",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "customerLogo",
                    label: "Customer Logo",
                    type: "file",
                    required: false,
                    readOnly: false,
                },
                {
                    name: "customerIncorporationDate",
                    label: "Incorporation Date",
                    type: "date",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "dialCode",
                    label: "Dial Code",
                    type: "number",
                    placeholder: "e.g. 91",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "phone",
                    label: "Phone",
                    type: "text",
                    placeholder: "e.g. 9876543210",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "companyId",
                    label: "Company",
                    type: "company-select",
                    required: true,
                    defaultValue: "",
                    readOnly: true,
                },
                {
                    name: "country",
                    label: "Country",
                    type: "text",
                    placeholder: "e.g. India, USA",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "state",
                    label: "State",
                    type: "text",
                    placeholder: "e.g. Maharashtra, California",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "city",
                    label: "City",
                    type: "text",
                    placeholder: "e.g. Mumbai, Los Angeles",
                    required: false,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "AddressLineOne",
                    label: "Address Line 1",
                    type: "text",
                    placeholder: "e.g. 123 Main St",
                    required: false,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "postalCode",
                    label: "Postal Code",
                    type: "number",
                    placeholder: "e.g. 400001",
                    required: false,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "ownerFirstName",
                    label: "Owner First Name",
                    type: "text",
                    placeholder: "e.g. John",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "ownerLastName",
                    label: "Owner Last Name",
                    type: "text",
                    placeholder: "e.g. Doe",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "ownerEmail",
                    label: "Owner Email",
                    type: "email",
                    placeholder: "e.g. john.doe@acme.com",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "ownerPhone",
                    label: "Owner Phone",
                    type: "text",
                    placeholder: "e.g. 9876543210",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "ownerDialCode",
                    label: "Owner Dial Code",
                    type: "number",
                    placeholder: "e.g. 91",
                    required: false,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "ownerDob",
                    label: "Owner Date of Birth",
                    type: "date",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                },
                {
                    name: "status",
                    label: "Status",
                    type: "select",
                    required: true,
                    defaultValue: "Active",
                    readOnly: false,
                    options: [
                        { label: "Active", value: "Active" },
                        { label: "Inactive", value: "Inactive" },
                    ],
                },
            ],
        },
    },
};
