import { PackageFormSchema, PackageUpdateSchema } from "../../Zod";

export const packageFormConfig = {
    contexts: {
        "package-add": {
            mode: "add",
            title: "Package",
            api: {
                method: "POST",
                endpoint: "package-add",
                module: "package",
            },
            schema: PackageFormSchema,
            submitButtonText: "Save",
            loadingButtonText: "Creating...",
            successMessage: "Package created successfully",
            fields: [
                {
                    name: "packageName",
                    label: "Package Name",
                    type: "text",
                    placeholder: "e.g. Box, Pallet, Carton",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "description",
                    label: "Description",
                    type: "textarea",
                    placeholder: "e.g. Standard outer carton for bulk shipment",
                    required: false,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "companyId",
                    label: "Company",
                    type: "company-select",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "status",
                    label: "Status",
                    type: "select",
                    required: true,
                    defaultValue: "Active",
                    readOnly: false,
                    hidden: false,
                    options: [
                        { label: "Active", value: "Active" },
                        { label: "Inactive", value: "Inactive" },
                    ],
                },
            ],
        },
        "package-update": {
            mode: "update",
            title: "Edit Package",
            api: {
                fetchEndpoint: "package-details",
                method: "PUT",
                endpoint: "package-update",
                module: "package",
            },
            schema: PackageUpdateSchema,
            submitButtonText: "Update Package",
            loadingButtonText: "Updating...",
            successMessage: "Package updated successfully",
            fields: [
                {
                    name: "packageName",
                    label: "Package Name",
                    type: "text",
                    placeholder: "e.g. Box, Pallet, Carton",
                    required: true,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "description",
                    label: "Description",
                    type: "textarea",
                    placeholder: "e.g. Standard outer carton for bulk shipment",
                    required: false,
                    defaultValue: "",
                    readOnly: false,
                    hidden: false,
                },
                {
                    name: "companyId",
                    label: "Company",
                    type: "company-select",
                    required: true,
                    defaultValue: "",
                    readOnly: true,
                    hidden: false,
                },
                {
                    name: "status",
                    label: "Status",
                    type: "select",
                    required: true,
                    defaultValue: "Active",
                    readOnly: false,
                    hidden: false,
                    options: [
                        { label: "Active", value: "Active" },
                        { label: "Inactive", value: "Inactive" },
                    ],
                },
            ],
        },
    },
};
